### ISSUE TITLE
Fuses added or issue resolved

### ISSUE THREAD

**Issue by FernandaPsihas** [FernandaPsihas/TinyTPC#11]

**Comment by FernandaPsihas** [comment]
Confirmed with ORC people that Fuses up to 2 A are reasonable. Checking our options starting with these and will consult Joe on it: 
(https://www.mouser.com/ProductDetail/Bussmann-Eaton/HLQ-1-6-10?qs=TNh9aA0PEuKI5xn%252BSDKWvg%3D%3D)
(https://www.mouser.com/c/circuit-protection/fuse-holders/fuse-holder/?current%20rating=1.6%20A~~2%20A&rp=circuit-protection%2Ffuse-holders%2Ffuse-holder%7C~Current%20Rating)
(https://www.mouser.com/c/circuit-protection/fuses/?q=2A%20Fast-Blow%20Fuse&body%20style=In%20Line%20Fuses&current%20rating=1.6%20A~~2.0%20A&rp=circuit-protection%2Ffuses%7C~Current%20Rating)

**Comment by FernandaPsihas** [comment]
actually what about these ones? (https://www.mouser.com/ProductDetail/Bussmann-Eaton/BK-ATM-2?qs=sGAEpiMZZMsIz3CjQ1xegWrlMY7vL59hf9i2S8FCL%252B0%3D)

**Comment by FernandaPsihas** [comment]
Got confirmation from Joe that these will work: 

- 4x [fuse](https://www.mouser.com/ProductDetail/Bussmann-Eaton/BK-ATM-2?qs=sGAEpiMZZMsIz3CjQ1xegWrlMY7vL59hf9i2S8FCL%252B0%3D)
- 4x [holder](https://www.mouser.com/ProductDetail/Bussmann-Eaton/HHM?qs=yHx7kt6%2FI%2FlCjxFAn851Mg%3D%3D)

@jzennamo can we buy these pretty please?

**Comment by jzennamo** [comment]
Order is placed!

**Comment by FernandaPsihas** [comment]
Need to buy the holders with the smaller gauge ...... 
- 4x [holder](https://www.digikey.com/en/products/detail/eaton---bussmann-electrical-division/BK%2FHHL-R/2173016?utm_adgroup=Fuseholders&utm_source=google&utm_medium=cpc&utm_campaign=Shopping_Product_Circuit%20Protection_NEW&utm_term=&utm_content=Fuseholders&gclid=CjwKCAiA3pugBhAwEiwAWFzwdUYesfZ1y-9rezUs3lLW6PgofLqqH-q_Uypl6nTgVE0GOOdJvG5NJxoCUYYQAvD_BwE)
