### ISSUE TITLE
Purchase copper board

### ISSUE THREAD

**Issue by FernandaPsihas** [FernandaPsihas/TinyTPC#14]
Wait for dimensions from #20

**Comment by FernandaPsihas** [comment]
we need at least 2 7.5x8.5 boards, mcmaster has a 36x24 which is cheaper than 2 18x12s 
https://www.mcmaster.com/8521K84/

**Comment by FernandaPsihas** [comment]
Called mcmaster to ask if the 2 sides are electrically isolated, they will send me an email. In the meantime will look for thicker boards from another vendor.

**Comment by FernandaPsihas** [comment]
Confirmed with mcmaster that both sides are electrically isolated and with Joe that 1/8 inch is ok. 

This is ok for purchase @jzennamo  https://www.mcmaster.com/8521K84/

**Comment by jzennamo** [comment]
Order 2 or 1?

**Comment by jzennamo** [comment]
Ordered.
