### ISSUE TITLE
Purchase components for ribbon cable flange

### ISSUE THREAD

**Issue by FernandaPsihas** [FernandaPsihas/TinyTPC#17]

**Comment by FernandaPsihas** [comment]
After talking to Joe, the adaptor alternative is doable. He can make a connector between the 50pin and the make 34 pin connectors. We would need to purchase:

- [50 pin flange] (https://www.accuglassproducts.com/50d-600-50-Pin-Feedthrough-6.00-CF-Flange)
- [Female 50 pin connector] (https://www.accuglassproducts.com/uhv-connector-50d-female)
- [Male 50 pin connector] (https://www.accuglassproducts.com/uhv-connector-50d-male)
- 2x [34pin male connector] (https://www.digikey.com/en/products/detail/samtec-inc/SHF-117-01-L-D-SM/6678658)

That's like $1400 worth of stuff tho, does that seem reasonable @jzennamo ? If yes, I can make a diagram with these part numbers attached and confirm with Flor and Joe that this will be ok so we can purchase.

**Comment by FernandaPsihas** [comment]
Discussed with Flor who approved the plan. Flor says the connectors might not have to be UHV rated so will move to purchase flange, 34pin male connectors, a ribbon cable, and a cable for the warm side of this connection: https://www.accuglassproducts.com/air-service-cable-assembly-50d  This should be sufficient to start working on the warm side adaptor.  We will still need one more connector for the inside but we can finalize that once Joe starts working. 

The missing connector will be one of these 2: 
https://www.accuglassproducts.com/connector-cable-50-way-male-0 
https://www.accuglassproducts.com/connector-cable-50-way-female-0 
 
 ALMOST ready to purchase the followoing: 
 - 1x [50 pin flange] (https://www.accuglassproducts.com/50d-600-50-Pin-Feedthrough-6.00-CF-Flange)
 - 2x [34pin male connector] (https://www.digikey.com/en/products/detail/samtec-inc/SHF-117-01-L-D-SM/6678658)
 - 1x [50D cable] https://www.accuglassproducts.com/air-service-cable-assembly-50d 
 - 1x RIBBON CABLE 
 
Will be ready to purchase **as soon as I can find the right ribbon cable** which is identical to the one we already have and I cannot for the life of me figure it out......... 
 @jzennamo do you have the link for it? I have not been able to get from the connector to the cable on the web.....

**Comment by FernandaPsihas** [comment]
I have narrowed it to [these options](https://www.digikey.com/en/products/filter/rectangular-cable-assemblies/450?s=N4IgjCBcoEwBxVAYygMwIYBsDOBTANCAPZQDaIALAAwUDsAbAodXfQJwgC6hADgC5QQAZT4AnAJYA7AOYgAvoTgJoIFJAw4CxMuDZUArAGZ9XXgMjCxU2QpB7EqtFjyESkcmBhhDMeqZD8giISMvKEYBEcKmoaLtruILRUMDD%2BgRbB1mG6cFHITpquOlRctgC0ENEFcW7k9J6ltn4q4gAmgoa0IGZBVqGEfACePLiCrdgocnJAA) and asked Antonio and Joe. Will try to move forward with purchase today or tomorrow with whatever answer I get.

**Comment by jzennamo** [comment]
I believe the cable was a custom LBNL build, I think Andy would know for sure if there is a stock item for it, but I can take a look in the google drive

**Comment by jzennamo** [comment]
I think here is the schematic of the wire that was ordered:
https://docs.google.com/spreadsheets/d/1C3lrtdcu3tquPc4yoteB_x0OwNt9yraU/edit?usp=sharing&ouid=103152155545601451171&rtpof=true&sd=true

**Comment by FernandaPsihas** [comment]
Woot! Can we order these please @jzennamo ? 

- [ ] 1x [50 pin flange](https://www.accuglassproducts.com/50d-600-50-Pin-Feedthrough-6.00-CF-Flange)
- [ ] 2x [34pin male connector](https://www.digikey.com/en/products/detail/samtec-inc/SHF-117-01-L-D-SM/6678658)
- [ ] 1x [50D cable](https://www.accuglassproducts.com/air-service-cable-assembly-50d)
- [ ] 1x {RIBBON CABLE](https://www.digikey.com/en/products/detail/samtec-inc/FFTP-17-D-18-00-01-N/6695757)

**Comment by FernandaPsihas** [comment]
Linda has saved the day with a much more reasonable alternative.
https://www.accuglassproducts.com/hv-strain-relief-50d (need 2)
https://www.accuglassproducts.com/gold-sockets-female-type-t-2-25-pack (need 64 total)
The green part that holds the sockets is missing here and maybe also the connector. Linda will send it to me. Also the image to explain this once I forget all the right terms for all the components.

**Comment by FernandaPsihas** [comment]
Talked to Linda and Rachel extensively. Joe's setup would not yield a mechanically stable connector so we are going with something more robust. These connectors receive pins, which will also make the job much faster. 

Can we please purchase these @jzennamo ? 

[] 1x [RIBBON CABLE - FFSD-17-D-77.00-01-N](https://www.digikey.com/en/products/detail/samtec-inc/FFSD-17-D-77-00-01-N/7237982  ) 

[] 2x [Connector that takes in pins - HV Connector - 50D - Female ](https://www.accuglassproducts.com/hv-connector-50d-female)
 
[]  2x [Casing -  HV Strain Relief - 50D](https://www.accuglassproducts.com/hv-strain-relief-50d )
 
[] 3x  [Pins - Gold Sockets - Female (TYPE: T-2) 25-Pack ( 26-30 AWG )](https://www.accuglassproducts.com/gold-sockets-female-type-t-2-25-pack?part-number=111653)

**Comment by jzennamo** [comment]
Order placed.
